### ISSUE TITLE
Renderer question & possible refactor

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1136]
- [ ] What is mean by common props https://github.com/codelab-ai/codelab.ai/blob/518f8752b01523cb7cb8f06f32383861484d9f0c/libs/frontend/presenter/container/src/providers/RenderProvider.tsx#L29

We could have an enum of props priority numbered 0 - 5 etc and have description naming for them.

**Comment by antonmihaylov** [comment]
This comment was written earlier when we had fewer props, common props here refers to the props comming from atomFactory, since they are common to all elements.

Right now the priority of the props is defined by the order of the render pipe, so I think it's pretty clear

![image](https://user-images.githubusercontent.com/57956282/135748463-1fea41a8-c4c2-408d-9cff-73946e58bee9.png)
