### ISSUE TITLE
Import logic causes unclear service layer code

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1227]
I came across the `Create Page` use case & found this line https://github.com/codelab-ai/codelab.ai/blob/575521dc1d730c9d2a04321d0b2289b5ff3d42b0/libs/backend/modules/page/src/use-cases/create-page/create-page.input.ts#L12-L13

It look me a while to understand why we have a `rootElement`, then only understood it after seeing the commit for this line, which was the import/export feature.

If we import a page, we'll have elements assigned underneath.

---

But this is mixing unrelated use cases together & causes confusion. A `Create Page` use case should only be concerned with creating a page.

This type of conditional logic should be avoided, the use case should have a clear & single responsibility.

---

Instead, we should handle it in the Import Use Case. You could have Import Use Case delegate to the required services. For example, create the page, then create elements under the page.

**Comment by antonmihaylov** [comment]
The reason for this change is that Import App use case relies on Create Page service to, well.. create the page. 

Create page use case still does exactly what it says it does - creates the page, only now it allows more flexibility in its usage by allowing customizing the root element, which otherwise was automatically generated.

The other option would be to repeat the same logic for creating a page in the Import App service, which will cause repetition and will be harder to maintain.

We can't just create the page, then create elements under the page, because we must be able to modify the root element itself, which is otherwise generated in the CreatePageService automatically. We could create the default, then update it, but I believe this is more confusing

**Comment by webberwang** [comment]
The root element is just a dummy root node to old the elements, so couldn't we have create page auto-generate it. Then the import can attach to this root element.

**Comment by antonmihaylov** [comment]
The goal of the import/export features is to be able to export something and then import it in the same exact state, right?
Users can normally modify the root element, for example, add a Layout atom to it.

With what you're suggesting, we'd add an extra root element with every import
