### ISSUE TITLE
Create form inside app

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1298]
Inside our created app, we'll add a form using the atoms we have. Basically, start with ant design components to create a simple form

- [x] Create form

- `name` required string
- `email` required, simple email validation

On submit should console the validated object data

- [x] Test import / export app 

Related to https://github.com/codelab-ai/web/issues/1203

**Comment by rihnoo** [comment]
@webberwang  I found the issue preventing to create the child element in builder. [Video Link](https://www.loom.com/share/530c0272d0ab402aaeba5fd68d25e837)

I will try to debug it and fix.

**Comment by webberwang** [comment]
Thanks likely some issue in previous refactor

**Comment by rihnoo** [comment]
Fixed the issue mentioned in this [commit](https://github.com/codelab-ai/web/commit/0661a19fad89d34a6ab857bb1b70136c5ee30175)

**Comment by rihnoo** [comment]
@webberwang 
I found another issue which currently elements tree is not showing in builder. [Video Link](https://www.loom.com/share/318edc53f5d644ffb30fd53f9ec3bcb4)

This is because of [this line](https://github.com/codelab-ai/web/blob/master/libs/shared/core/src/tree/tree.service.ts#L165)
![image](https://user-images.githubusercontent.com/34818311/150690576-46b02bf9-d088-4c91-a4ca-b37a0ff941a3.png)

`isRoot` property doesn't exist in DataNode so it's always undefined.  that prevents the element tree from being displayed.

I will try to resolve this issue.

**Comment by rihnoo** [comment]
via Hubstaff
User: Ming Lee

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 01/21/22 - 01/28/22
Work session total: 22:35:03
Billable: Yes

Grand total: 22:35:03
