### ISSUE TITLE
Migrate Element module to Neo4j

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1414]

**Comment by assimhabeek** [comment]
## old approche
- Before using neo4j, we had two copies in the cache for each element. one by the graph endpoints and the other by calling `useGetElementQuery`. When hovering or selecting, The first request for each element will hit the server and create a duplication for the element in the cache in addition to the one already loaded by the graph endpoint. and after each invalidation it will re-fetch this element with the whole graph. I also notice that it is re-fetching after a small provide of time, which shouldn't happen unless the component is unmounted, so this is another performance cost.  [read more](https://redux-toolkit.js.org/rtk-query/usage/cache-behavior#cache-lifetime--subscription-example) 
- In addition we provided the graph tags like this. `{
          type: ELEMENT_CACHE_TAG,
          id: v.id,
        }`  means on each vertices add/update/delete re-fetch the graph.   [read more](https://nicedoc.io/reactjs/redux/blob/master/docs/tutorials/essentials/part-8-rtk-query-advanced.md#invalidating-specific-items) 
``` 
    GetElementGraph: {
      providesTags: (result, _, arg) => [
        {
          type: ELEMENT_GRAPH_CACHE_TAG,
          id: arg.variables?.input.where.id ?? undefined,
        },
        ...(result?.getElementGraph.vertices.map((v) => ({
          type: ELEMENT_CACHE_TAG,
          id: v.id,
        })) ?? []),
      ],
    },
```  
So, using the local state introduces  gain in performance since we are re-loading it on each time 
# Suggested approach  
- Element schema will contain a field named `edges` we require once when loading pages. 
```
fragment ElementEdge on ElementEdge {
  source
  target
  order
}

fragment Page on Page {
  id
  name
  rootElement {
    id
    name
    edges {
      ...ElementEdge
    }
  }
}
```  
- Using the edges we load all referenced vertices once using auto-generated `GetElements` endpoint 
- OnSelect and onHover will read from local State since there is no reason for additional requests 
- Use manual cache manipulation on element add/update and remove to minimize the calls for the huge vertices query. This will not prevent repeated calls but reduces them as possible 
- Using `createEntityAdapter` isn't that interesting since each endpoint stores its cache separately. so we will only normalize how we store cache and not de-duplicate it    [read more here](https://nicedoc.io/reactjs/redux/blob/master/docs/tutorials/essentials/part-8-rtk-query-advanced.md#normalized-vs-document-caches)
